#!/usr/bin/env node
/* Generate /gz-ux.js from audit lists + catalog: per-slug config for
 * onboarding overlay (164 no-guidance games), restart button (173), mute (343).
 * Feature notes:
 *  - head-injected, everything binds at DOMContentLoaded; zero pre-DCL DOM work
 *  - skips ALL features when window.__dls present (verifier harness — guarantees
 *    engine verifiers see a byte-identical DOM; real-browser UX unaffected)
 *  - overlay removes itself from DOM on dismiss (no pointer-events residue)
 * Usage: node gen-gz-ux.js  (reads /tmp/ux-lists.json, writes /gz-ux.js) */
const fs = require('fs');
const path = require('path');
const repo = path.resolve(__dirname, '..', '..');

const lists = JSON.parse(fs.readFileSync('/tmp/ux-lists.json', 'utf8'));
const catalog = {};
{
  const gd = fs.readFileSync(path.join(repo, 'js', 'games-data.js'), 'utf8');
  const re = /\{name:"((?:[^"\\]|\\.)*)"[^}]*?url:"\/([^"]+)\/"[^}]*?desc:"((?:[^"\\]|\\.)*)"/g;
  let m; while ((m = re.exec(gd))) {
    try { catalog[m[2]] = { name: JSON.parse('"' + m[1] + '"'), desc: JSON.parse('"' + m[3] + '"') }; } catch {}
  }
}
function firstSentence(desc) {
  let d = (desc || '').replace(/^play [^!]*!?\s*/i, '').replace(/^[-–—\s]+/, '');
  const cut = d.split(/(?<=[.!?])\s/)[0] || d;
  return (cut.length > 160 ? cut.slice(0, 157) + '…' : cut).trim();
}
const CFG = {};
for (const slug of lists.onboarding) {
  const c = catalog[slug];
  CFG[slug] = CFG[slug] || {};
  CFG[slug].onboard = c ? { t: c.name, d: firstSentence(c.desc) } : { t: '' }; // empty t => derive from <title> at runtime
}
for (const slug of lists.restart) { CFG[slug] = CFG[slug] || {}; CFG[slug].restart = 1; }
for (const slug of lists.mute) { CFG[slug] = CFG[slug] || {}; CFG[slug].mute = 1; }

const js = `/* gz-ux.js v1 — shared onboarding/HUD layer (GameZipper UX plan W2/W3/W5).
 * Generated by _optimization/scripts/gen-gz-ux.js from ux-audit matrix; do not hand-edit config.
 * Zero engine interference: no pre-DCL DOM work, no stopPropagation/preventDefault,
 * overlay node removed on dismiss, and ALL features skip when the verifier
 * harness is detected (window.__dls) so verify_engine.js sees an identical DOM. */
(function () {
  'use strict';
  if (window.__dls) return; // engine-verifier harness compatibility gate
  var CFG = ${JSON.stringify(CFG)};
  var slug = location.pathname.replace(/^\\/+|\\/+$|\\.html$/g, '') || 'index';
  var c = CFG[slug];
  if (!c) { try { c = CFG[slug.replace(/\\/$/, '')]; } catch (e) {} }
  if (!c) return;

  /* ---- mute state patched at head-time: before any game script runs ---- */
  var muted = false;
  try { muted = localStorage.getItem('gzux-mute') === '1'; } catch (e) {}
  var GZCTX = [];
  if (c.mute) {
    try {
      var OP = HTMLMediaElement.prototype.play;
      HTMLMediaElement.prototype.play = function () { if (muted) this.muted = true; return OP.apply(this, arguments); };
      var AC = window.AudioContext || window.webkitAudioContext;
      if (AC) {
        var W = function () { var ctx = new AC(); GZCTX.push(ctx); if (muted) { try { ctx.suspend().catch(function () {}); } catch (e) {} } return ctx; };
        W.prototype = AC.prototype; Object.setPrototypeOf(W, AC);
        window.AudioContext = W; if (window.webkitAudioContext) window.webkitAudioContext = W;
      }
    } catch (e) {}
  }
  function applyMute() {
    var ms = document.querySelectorAll('audio,video');
    for (var i = 0; i < ms.length; i++) ms[i].muted = muted;
    for (var j = 0; j < GZCTX.length; j++) { try { muted ? GZCTX[j].suspend().catch(function () {}) : GZCTX[j].resume().catch(function () {}); } catch (e) {} }
  }

  function el(tag, css, txt) {
    var e = document.createElement(tag);
    if (css) e.style.cssText = css;
    if (txt != null) e.textContent = txt;
    return e;
  }

  function onboard() {
    var key = 'gzux-ok-' + slug, seen = false;
    try { seen = !!localStorage.getItem(key); } catch (e) {}
    if (seen || !c.onboard) return;
    var title = c.onboard.t || (document.title.split(/[|–—-]/)[0] || 'Game').trim();
    var desc = c.onboard.d || 'Jump in and explore — the game starts right away.';
    var touch = 'ontouchstart' in window || navigator.maxTouchPoints > 0;
    var controls = touch ? 'Tap and drag to play.' : 'Click / drag to play. Keyboard supported where shown.';

    var root = el('div', 'position:fixed;inset:0;z-index:2147483000;display:flex;align-items:center;justify-content:center;background:rgba(10,12,20,.72);backdrop-filter:blur(2px);font-family:system-ui,Segoe UI,Arial,sans-serif;color:#fff');
    root.id = 'gz-ux-onboard';
    var card = el('div', 'background:#171a26;border:1px solid #2c3145;border-radius:16px;padding:28px 26px;max-width:min(420px,86vw);box-shadow:0 18px 60px rgba(0,0,0,.5);text-align:center');
    card.appendChild(el('div', 'font-size:22px;font-weight:700;margin-bottom:10px', title));
    card.appendChild(el('div', 'font-size:14.5px;line-height:1.55;color:#c6cbdd;margin-bottom:8px', desc));
    card.appendChild(el('div', 'font-size:13px;color:#8b93ad;margin-bottom:18px', controls));
    var btn = el('button', 'background:linear-gradient(135deg,#5b8cff,#7c5bff);color:#fff;border:0;border-radius:12px;padding:13px 34px;font-size:17px;font-weight:700;cursor:pointer', '▶  Start Game');
    btn.setAttribute('aria-label', 'Start game');
    card.appendChild(btn);
    root.appendChild(card);
    document.body.appendChild(root);
    function close() {
      try { localStorage.setItem(key, '1'); } catch (e) {}
      if (root.parentNode) root.parentNode.removeChild(root); // full removal — no residue
      document.removeEventListener('keydown', onKey, true);
    }
    function onKey(e) { if (e.key === 'Enter' || e.key === 'Escape') { e.stopPropagation(); close(); } }
    document.addEventListener('keydown', onKey, true);
    btn.addEventListener('click', close);
  }

  function hud() {
    if (!c.restart && !c.mute) return;
    var bar = el('div', 'position:fixed;right:10px;bottom:10px;z-index:2147482000;display:flex;gap:8px;font-family:system-ui,Segoe UI,Arial,sans-serif');
    bar.id = 'gz-ux-hud';
    function chip(txt, label, fn) {
      var b = el('button', 'width:42px;height:42px;border-radius:50%;border:1px solid rgba(255,255,255,.25);background:rgba(15,18,28,.62);color:#fff;font-size:19px;cursor:pointer;backdrop-filter:blur(3px);display:flex;align-items:center;justify-content:center;padding:0', txt);
      b.setAttribute('aria-label', label); b.title = label;
      b.addEventListener('click', fn);
      return b;
    }
    if (c.restart) bar.appendChild(chip('↻', 'Restart', function () {
      if (typeof window.gzRestart === 'function') window.gzRestart();
      else location.reload();
    }));
    if (c.mute) {
      var mb = chip(muted ? '🔇' : '🔊', muted ? 'Unmute' : 'Mute', function () {
        muted = !muted;
        try { localStorage.setItem('gzux-mute', muted ? '1' : '0'); } catch (e) {}
        applyMute();
        mb.textContent = muted ? '🔇' : '🔊'; mb.title = mb.setAttribute('aria-label', muted ? 'Unmute' : 'Mute'), (muted ? 'Unmute' : 'Mute');
      });
      bar.appendChild(mb);
    }
    document.body.appendChild(bar);
    applyMute();
  }

  function ready() { try { onboard(); hud(); } catch (e) {} }
  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', ready);
  else ready();
})();
`;
fs.writeFileSync(path.join(repo, 'gz-ux.js'), js);
console.log('gz-ux.js written:', (js.length / 1024).toFixed(1) + 'KB, config entries:', Object.keys(CFG).length,
  '| onboarding:', lists.onboarding.length, 'restart:', lists.restart.length, 'mute:', lists.mute.length);
