#!/usr/bin/env node
/* circuit-logic verifier — 65 pipe-rotation puzzles: each level generated by the
 * engine's own seeded generator carries solutionRotation per tile; the verifier
 * rotates tiles to their solution orientation through REAL canvas clicks (tile center
 * -> rotateTile) and confirms the engine's own checkWin/triggerWin fires. */
const { bootGame } = require('../_optimization/scripts/harness-lib.js');
const g = bootGame('circuit-logic', { inject: {
  anchor: 'function rotateTile(x, y) {',
  exports: `globalThis.__Q = {
    total: () => TOTAL_LEVELS,
    start: (l) => { showScreen('game'); startLevel(l, false); },
    tiles: () => levelData.tiles.map(row => row.map(t => ({ r: t.rotation, s: t.solutionRotation }))),
    grid: () => levelData.gridSize,
    won: () => winAnimating === true,
    screen: () => currentScreen,
    tutorial: () => showTutorial,
  };`,
} });

let pass = 0, fail = 0; const fails = [];
const T = (n, ok, info) => { if (ok) pass++; else { fail++; fails.push(n + ': ' + info); } };
const cv = () => g.els.gameCanvas;

T('boot-clean', g.loadErrors.length === 0, JSON.stringify(g.loadErrors[0] || '').slice(0, 120));
const N = g.call('__Q.total()');
T('levels-exist', N === 65, 'n=' + N);

function clickTile(x, y, gs, canvasW) {
  const cell = canvasW / gs;
  cv().dispatch('click', { clientX: (x + 0.5) * cell, clientY: (y + 0.5) * cell, preventDefault() {} });
}

const solved = [];
for (let l = 1; l <= N; l++) {
  g.timers.length = 0; // stale win-screen timers from the previous level fire mid-level and steal the click path
  g.call(`__Q.start(${l})`); g.pump(3);
  // dismiss tutorial overlay clicks for early levels
  for (let t = 0; t < 6 && g.call('__Q.tutorial()'); t++) { clickTile(0, 0, 8, 480); g.pump(2); }
  const gs = g.call('__Q.grid()');
  const tiles = g.call('__Q.tiles()');
  for (let y = 0; y < gs; y++) for (let x = 0; x < gs; x++) {
    const t = tiles[y][x];
    const need = ((t.s - t.r) % 4 + 4) % 4;
    for (let k = 0; k < need; k++) { clickTile(x, y, gs, 480); g.pump(1); }
  }
  g.pump(30); // triggerWin timer
  if (g.call('__Q.won()')) solved.push(l); else fails.push('L' + l + ' solution rotation not won');
}
T('levels-solved', solved.length === N, solved.length + '/' + N + ' solved:[' + solved.join(',') + '] missing:[' + [...Array(N).keys()].map(x => x + 1).filter(x => !solved.includes(x)).slice(0, 20).join(',') + (solved.length < N ? '...' : '') + ']');

T('no-vm-errors', !(g.sandbox.__errors || []).some(e => /TypeError|ReferenceError/.test(e)),
  JSON.stringify((g.sandbox.__errors || []).find(e => /TypeError|ReferenceError/.test(e)) || '').slice(0, 120));

const out = { pass, fail, total: pass + fail, verdict: fail === 0 ? 'PASS' : 'FAIL', fails: fails.slice(0, 6), extra: { solved: solved.length + '/' + N } };
console.log('circuit-logic: ' + solved.length + '/' + N + ' circuits solved via real tile clicks: ' + out.verdict);
console.log(JSON.stringify(out));
process.exit(fail === 0 ? 0 : 1);
