#!/usr/bin/env node
/* GENERATED in-engine verifier for kuromasu (spec: _optimization/scripts/verifier-spec.md, type A).
 * 26 of the 30 original static clue sets admitted NO solution under the engine's own semantics
 * (verified exhaustively; fix wave A5 2026-08-16) and were regenerated by a witness-first
 * generator carrying an EMBEDDED solution string (index.html LEVELS[].sol). Those are validated
 * against full rules (clue = rowBlack+colBlack per engine countVisible; no 2x2 black; whites
 * connected) and PLAYED through the engine's toggleCell -> checkSolution -> onComplete.
 * The 4 surviving original levels (no embedded sol) + the daily (7x7 mulberry32 generator) are
 * solved by an INDEPENDENT two-phase solver (column-target enumeration + per-cell DFS with
 * frontier-connectivity pruning) and replayed the same way. Win requires the completeOverlay
 * shown AND kuromasu_save.completed[level.id] persisted.
 * Usage: node kuromasu/verify_engine.js   (cwd = repo root) */
const fs = require('fs');
const vm = require('vm');
const path = require('path');

const SLUG = 'kuromasu';
const html = fs.readFileSync(path.join(__dirname, 'index.html'), 'utf8');
const scripts = [...html.matchAll(/<script(?![^>]*src=)(?![^>]*application\/ld\+json)[^>]*>([\s\S]*?)<\/script>/g)].map(m => m[1]);
let code = scripts.join('\n');
/* SOURCE SURGERY: engine is an IIFE with no exports; inject an internals accessor just before
 * the engine's own init tail (index.html untouched otherwise). */
const ANCHOR = 'showMenu();\ngameLoop(0);';
if (!code.includes(ANCHOR)) { console.error('surgery anchor not found'); process.exit(1); }
code = code.replace(ANCHOR, 'window.__KU={LV:function(){return LEVELS},GS:function(){return gridSize},ST:function(){return state},CL:function(){return completedLevels},load:loadLevel,toggle:toggleCell,daily:generateDailyPuzzle,getDaily:function(){return dailyPuzzle}};\n' + ANCHOR);

function mkAny() {
  const f = function () { return anyP; };
  const anyP = new Proxy(f, {
    get(t, p) {
      if (p === Symbol.toPrimitive) return () => 0;
      if (p === 'length') return 0;
      if (!(p in t)) t[p] = mkAny();
      return t[p];
    },
    set() { return true; },
    apply() { return anyP; },
  });
  return anyP;
}
function mkEl(extra) {
  const el = {
    id: '', className: '', style: { setProperty: () => {} }, dataset: {}, textContent: '', innerHTML: '', value: '',
    children: [], disabled: false, hidden: false,
    classList: {
      _set: new Set(),
      add(...cs) { cs.forEach(c => this._set.add(c)); },
      remove(...cs) { cs.forEach(c => this._set.delete(c)); },
      toggle(c, f) { const on = f === undefined ? !this._set.has(c) : !!f; on ? this._set.add(c) : this._set.delete(c); return on; },
      contains(c) { return this._set.has(c); },
    },
    addEventListener: () => {}, removeEventListener: () => {}, dispatchEvent: () => {},
    appendChild: function (c) { return c; }, removeChild: function (c) { return c; }, remove: () => {},
    querySelector: () => mkEl(), querySelectorAll: () => [],
    getBoundingClientRect: () => ({ left: 0, top: 0, width: 500, height: 500, right: 500, bottom: 500 }),
    setAttribute: () => {}, getAttribute: () => '',
    getContext: () => mkAny(),
    focus: () => {}, blur: () => {}, click: () => {},
  };
  Object.assign(el, extra || {});
  return el;
}
const BODY = mkEl();
const elsById = new Map();
const timerErrors = [];
const sandbox = {
  console, Math: Object.assign(Object.create(Math), Math), Date, JSON, Array, Object, Set, Map, Number, String, Boolean,
  parseInt, parseFloat, isNaN, isFinite, Symbol, RegExp, Promise, Uint8Array, Uint32Array, Int32Array, Float32Array,
  Error, TypeError, alert: () => {}, prompt: () => '', confirm: () => true,
  window: { addEventListener: () => {}, removeEventListener: () => {}, innerWidth: 1280, innerHeight: 720, devicePixelRatio: 1,
    matchMedia: () => ({ matches: false, addEventListener: () => {}, addListener: () => {} }), scrollTo: () => {},
    location: { href: 'https://localhost/' }, dispatchEvent: () => {} },
  document: {
    getElementById: (id) => { if (!elsById.has(id)) elsById.set(id, mkEl({ id })); return elsById.get(id); },
    querySelector: () => mkEl(), querySelectorAll: () => [],
    addEventListener: () => {}, removeEventListener: () => {},
    createElement: () => mkEl(), createTextNode: (t) => ({ textContent: t }),
    body: BODY, documentElement: mkEl(), hidden: false, visibilityState: 'visible', readyState: 'complete', cookie: '',
  },
  adsbygoogle: { push: () => {} },
  localStorage: (() => { const m = {}; return { getItem: k => (k in m ? m[k] : null), setItem: (k, v) => { m[k] = String(v); }, removeItem: k => { delete m[k]; }, clear: () => { for (const k in m) delete m[k]; } }; })(),
  setInterval: () => 0, clearInterval: () => {},
  setTimeout: (fn) => { try { return fn && fn(); } catch (e) { timerErrors.push(String(e && e.message)); return 0; } },
  clearTimeout: () => {},
  requestAnimationFrame: () => 0, cancelAnimationFrame: () => {},
  performance: { now: () => Date.now() },
  fetch: () => Promise.resolve({ ok: true, json: () => Promise.resolve({}), text: () => Promise.resolve('') }),
  navigator: { userAgent: 'verify', maxTouchPoints: 1 },
  MutationObserver: function () { return { observe: () => {}, disconnect: () => {} }; },
  ResizeObserver: function () { return { observe: () => {}, disconnect: () => {} }; },
  IntersectionObserver: function () { return { observe: () => {}, disconnect: () => {} }; },
};
sandbox.window.document = sandbox.document;
sandbox.window.localStorage = sandbox.localStorage;
sandbox.window.performance = sandbox.performance;
sandbox.window.navigator = sandbox.navigator;
sandbox.window.setTimeout = sandbox.setTimeout;
sandbox.window.requestAnimationFrame = sandbox.requestAnimationFrame;
sandbox.globalThis = sandbox;
sandbox.__timerErrors = timerErrors;
sandbox.__ONLY = process.env.ONLY || '';
const ctx = vm.createContext(sandbox);
let loadErr = null;
try { vm.runInContext(code, ctx, { filename: 'kuromasu-bundle.js' }); } catch (e) { loadErr = e; }
if (loadErr) { console.error('engine load error:', loadErr.stack || loadErr.message); console.log(JSON.stringify({ pass: 0, fail: 1, total: 1, verdict: 'FAIL' })); process.exit(1); }

const DRIVER = `(function(){
'use strict';
const KU=window.__KU;
/* Independent Kuromasu solver matching engine semantics exactly:
 * clue (r,c,v): (# black in row r) + (# black in col c) === v (clue cell itself always white);
 * no 2x2 all black; all non-black cells 4-connected.
 * Phase A: enumerate colBlack[] ONLY for columns that carry >=1 clue (clue-free columns are
 * unconstrained by any clue), pruning by row-sum bounds (clue (r,c,v) pins rowBlack[r]=v-colBlack[c]).
 * Phase B: row-pattern DFS (patterns grouped per black-count) realizing pinned row sums + exact
 * clue-column capacities, 2x2 pruning, white connectivity at the end. */
function solveKuro(size,clues){
 const R=size,C=size;
 const clueRow=[],clueCol=[],clueVal=[],clueAt={};
 for(var i=0;i<clues.length;i++){var cl=clues[i];clueRow.push(cl[0]);clueCol.push(cl[1]);clueVal.push(cl[2]);clueAt[cl[0]+','+cl[1]]=cl[2];}
 const rowFree=[];for(var r=0;r<R;r++){var n=0;for(var c=0;c<C;c++)if(clueAt[r+','+c]===undefined)n++;rowFree.push(n);}
 const colFree=[];for(var c=0;c<C;c++){var n=0;for(var r=0;r<R;r++)if(clueAt[r+','+c]===undefined)n++;colFree.push(n);}
 const cluesInCol=[];const clueCols=[];
 for(var c=0;c<C;c++){var a=[];for(var i=0;i<clues.length;i++)if(clueCol[i]===c)a.push(i);cluesInCol.push(a);if(a.length)clueCols.push(c);}
 const cluesInRow=[];for(var r=0;r<R;r++){var a=[];for(var i=0;i<clues.length;i++)if(clueRow[i]===r)a.push(i);cluesInRow.push(a);}
 /* most-constrained clue columns first */
 const colOrder=clueCols.slice();
 colOrder.sort(function(a,b){return (Math.min.apply(null,cluesInCol[a].map(function(i){return clueVal[i]}))+cluesInCol[a].length*3)-(Math.min.apply(null,cluesInCol[b].map(function(i){return clueVal[i]}))+cluesInCol[b].length*3);});
 /* per-row patterns grouped by black count */
 const pats=[];
 for(var r=0;r<R;r++){
  var free=[];for(var c=0;c<C;c++)if(clueAt[r+','+c]===undefined)free.push(c);
  var grp=[];for(var k=0;k<=free.length;k++)grp.push([]);
  for(var mask=0;mask<(1<<free.length);mask++){
   var p=new Array(C).fill(0),cnt=0;
   for(var b=0;b<free.length;b++)if((mask>>b)&1){p[free[b]]=1;cnt++;}
   grp[cnt].push(p);
  }
  pats.push(grp);
 }
 const freeBelow=[];for(var r=0;r<=R;r++){freeBelow.push([]);for(var c=0;c<C;c++){var n=0;for(var rr=r;rr<R;rr++)if(clueAt[rr+','+c]===undefined)n++;freeBelow[r][c]=n;}}
 var nodes=0,hitCap=false,budgetHit=false;const CAPN=8000000,DL=Date.now()+15000;const VEC_BUDGET=200000;
 const colBlack=new Array(C).fill(-1);
 function connectedOf(rows){
  var start=null,total=0;
  var white=[];for(var r=0;r<R;r++){white.push([]);for(var c=0;c<C;c++){white[r][c]=rows[r][c]===0;if(white[r][c]){total++;if(!start)start=[r,c];}}}
  if(!start)return false;
  var vis=new Set([start[0]+','+start[1]]);var q=[start];
  while(q.length){var t=q.shift();
   var d=[[-1,0],[1,0],[0,-1],[0,1]];
   for(var k=0;k<4;k++){var nr=t[0]+d[k][0],nc=t[1]+d[k][1],key=nr+','+nc;
    if(nr>=0&&nr<R&&nc>=0&&nc<C&&white[nr][nc]&&!vis.has(key)){vis.add(key);q.push([nr,nc]);}}}
  return vis.size===total;
 }
 var vecNodes=0;
 function frontierCell(g,r){
  var comp=[];for(var i=0;i<R;i++){comp.push([]);for(var j=0;j<C;j++)comp[i][j]=-1;}
  var ncomp=0,front=0,anyWhite=false;
  for(var i=0;i<=r;i++)for(var j=0;j<C;j++){
   if(g[i][j]===0&&comp[i][j]===-1){
    anyWhite=true;
    var q2=[[i,j]];comp[i][j]=ncomp;var touch=false;
    if(i===r)touch=true;
    while(q2.length){
     var t2=q2.pop();
     var dd=[[-1,0],[1,0],[0,-1],[0,1]];
     for(var k2=0;k2<4;k2++){
      var nr2=t2[0]+dd[k2][0],nc2=t2[1]+dd[k2][1];
      if(nr2>=0&&nr2<=r&&nc2>=0&&nc2<C&&g[nr2][nc2]===0&&comp[nr2][nc2]===-1){
       comp[nr2][nc2]=ncomp;
       if(nr2===r)touch=true;
       q2.push([nr2,nc2]);
      }
     }
    }
    if(touch)front++;
    ncomp++;
   }
  }
  if(!anyWhite)return false;
  return front===ncomp;
 }
 function phaseB(rowLo,rowHi){
  /* per-cell DFS (row-major free cells) with: exact clue-column needs, per-row black-count
   * bounds [rowLo,rowHi], 2x2 check at assignment, column reachability, frontier white
   * connectivity at each row end, and remaining-need vs remaining-capacity sum bound. */
  const g=[];for(var qr=0;qr<R;qr++){g.push([]);for(var qc=0;qc<C;qc++)g[qr][qc]=clueAt[qr+','+qc]!==undefined?0:-1;}
  const need=new Array(C);for(var qc=0;qc<C;qc++)need[qc]=colBlack[qc];
  const freeCells=[];const rowCells=new Array(R).fill(0);
  for(var qr=0;qr<R;qr++)for(var qc=0;qc<C;qc++)if(g[qr][qc]===-1){freeCells.push(qr*C+qc);rowCells[qr]++;}
  const freeBelowCell=[];for(var qr=0;qr<=R;qr++)freeBelowCell.push(new Array(C).fill(0));
  for(var qr=R-1;qr>=0;qr--)for(var qc=0;qc<C;qc++)freeBelowCell[qr][qc]=freeBelowCell[qr+1][qc]+(g[qr][qc]===-1?1:0);
  const rowUsed=new Array(R).fill(0);
  const sufMax=new Array(R+1).fill(0);
  for(var qr=R-1;qr>=0;qr--)sufMax[qr]=sufMax[qr+1]+rowHi[qr];
  const lastIdxInRow=new Array(R).fill(-1);
  for(var i=0;i<freeCells.length;i++)lastIdxInRow[(freeCells[i]/C)|0]=i;
  const firstIdxInRow=new Array(R).fill(-1);
  for(var i=freeCells.length-1;i>=0;i--)firstIdxInRow[(freeCells[i]/C)|0]=i;
  const rowOfIdx=[],colOfIdx=[];
  for(var i=0;i<freeCells.length;i++){rowOfIdx.push((freeCells[i]/C)|0);colOfIdx.push(freeCells[i]%C);}
  vecNodes=0;
  function recCell(i){
   if(++nodes>CAPN){hitCap=true;return false;}
   if(++vecNodes>VEC_BUDGET){budgetHit=true;return false;}
   if((vecNodes&65535)===0&&Date.now()>DL){hitCap=true;return false;}
   if(i===freeCells.length){
    for(var qc=0;qc<C;qc++)if(need[qc]>0)return false;
    var start=null,total=0;
    for(var qr=0;qr<R;qr++)for(var qc=0;qc<C;qc++)if(g[qr][qc]===0){total++;if(!start)start=[qr,qc];}
    if(!start)return false;
    var vis=new Set([start[0]+','+start[1]]);var q=[start];
    while(q.length){var t=q.shift();
     var dd=[[-1,0],[1,0],[0,-1],[0,1]];
     for(var k=0;k<4;k++){var nr=t[0]+dd[k][0],nc=t[1]+dd[k][1],key=nr+','+nc;
      if(nr>=0&&nr<R&&nc>=0&&nc<C&&g[nr][nc]===0&&!vis.has(key)){vis.add(key);q.push([nr,nc]);}}}
    return vis.size===total;
   }
   const r=rowOfIdx[i],c=colOfIdx[i];
   const isRowEnd=lastIdxInRow[r]===i;
   const beforeInRow=i-firstIdxInRow[r];
   const cellsLeftInRow=rowCells[r]-beforeInRow-1;
   function rowEndChecks(){
    if(rowUsed[r]<rowLo[r]||rowUsed[r]>rowHi[r])return false;
    if(!frontierCell(g,r))return false;
    var sn=0;for(var c2=0;c2<C;c2++)if(need[c2]>0)sn+=need[c2];
    if(sn>sufMax[r+1])return false;
    return true;
   }
   g[r][c]=0;
   var okW=true;
   if(rowUsed[r]+cellsLeftInRow<rowLo[r])okW=false;
   if(okW){
    if(isRowEnd){if(rowEndChecks()&&recCell(i+1))return true;}
    else if(recCell(i+1))return true;
   }
   var okB=true;
   if(need[c]===0)okB=false;
   else if(rowUsed[r]+1>rowHi[r])okB=false;
   else if(r>0&&c>0&&g[r-1][c-1]===1&&g[r-1][c]===1&&g[r][c-1]===1)okB=false;
   else if(need[c]-1>freeBelowCell[r+1][c])okB=false;
   if(okB){
    g[r][c]=1;need[c]--;rowUsed[r]++;
    if(isRowEnd){if(rowEndChecks()&&recCell(i+1))return true;}
    else if(recCell(i+1))return true;
    g[r][c]=0;need[c]++;rowUsed[r]--;
   }
   g[r][c]=-1;
   return false;
  }
  return recCell(0)?g:null;
 }

 var maxVof=new Array(C).fill(0);
 for(var c=0;c<C;c++)if(cluesInCol[c].length)maxVof[c]=Math.min(colFree[c],Math.min.apply(null,cluesInCol[c].map(function(i){return clueVal[i]})));
 /* arc consistency: clue (r,c,v) means rowBlack[r]+colBlack[c]=v exactly; iterate row-interval
  * <-> column-interval tightening to a fixpoint so phaseA enumerates a small domain */
 var colLo=new Array(C).fill(0),colHi=new Array(C).fill(0);
 for(var c=0;c<C;c++)colHi[c]=cluesInCol[c].length?maxVof[c]:0;
 var rLo=new Array(R),rHi=new Array(R);
 for(var r=0;r<R;r++){rLo[r]=0;rHi[r]=rowFree[r];}
 for(var it=0;it<20;it++){
  var changed=false;
  for(var i=0;i<clues.length;i++){
   var cr=clueRow[i],cc=clueCol[i],cv=clueVal[i];
   /* row range from col range: rb = cv - colBlack in [cv-colHi, cv-colLo] */
   var nlo=Math.max(rLo[cr],cv-colHi[cc]),nhi=Math.min(rHi[cr],cv-colLo[cc]);
   if(nlo!==rLo[cr]||nhi!==rHi[cr]){rLo[cr]=nlo;rHi[cr]=nhi;changed=true;}
   var clo=Math.max(colLo[cc],cv-rHi[cr]),chi=Math.min(colHi[cc],cv-rLo[cr]);
   if(clo!==colLo[cc]||chi!==colHi[cc]){colLo[cc]=clo;colHi[cc]=chi;changed=true;}
  }
  if(!changed)break;
 }
 solveKuro.domSum=0;
 for(var c=0;c<C;c++)if(cluesInCol[c].length)solveKuro.domSum+=(colHi[c]-colLo[c]+1);
 /* full recompute of per-row black-count bounds from current partial colBlack assignment:
  * assigned clue column -> exact pin (all pins in a row must agree); unassigned -> interval
  * [v-maxV, v] which must intersect. Returns null when infeasible. */
 function rowBounds(){
  const lo=new Array(R),hi=new Array(R),pin=new Array(R);
  for(var r=0;r<R;r++){lo[r]=0;hi[r]=rowFree[r];pin[r]=-1;}
  for(var i=0;i<clues.length;i++){
   var r=clueRow[i],c=clueCol[i],v=clueVal[i];
   if(colBlack[c]>=0){
    var rb=v-colBlack[c];
    if(rb<0||rb>rowFree[r])return null;
    if(pin[r]===-1)pin[r]=rb;
    else if(pin[r]!==rb)return null;
   }else{
    if(v-maxVof[c]>lo[r])lo[r]=v-maxVof[c];
    if(v<hi[r])hi[r]=v;
   }
   if(lo[r]>hi[r])return null;
   if(pin[r]>=0&&(pin[r]<lo[r]||pin[r]>hi[r]))return null;
  }
  return [lo,hi,pin];
 }
 function phaseA(ci){
  if(hitCap)return;
  if(++nodes>CAPN){hitCap=true;return;}
  if(ci===colOrder.length){
   solveKuro.leaves=(solveKuro.leaves||0)+1;
   var lr=rowBounds();
   if(!lr)return;
   var rowLo=[],rowHi=[];
   for(var r=0;r<R;r++){rowLo.push(Math.max(lr[2][r]>=0?lr[2][r]:lr[0][r],0));rowHi.push(lr[2][r]>=0?lr[2][r]:lr[1][r]);}
   for(var q2=0;q2<R;q2++)if(rowLo[q2]>rowHi[q2])return;
   var res=phaseB(rowLo,rowHi);
   if(res&&!phaseA.found){phaseA.found=res;hitCap=true;}
   return;
  }
  var c=colOrder[ci];
  for(var v=colLo[c];v<=colHi[c];v++){
   if(hitCap)return;
   colBlack[c]=v;
   if(rowBounds())phaseA(ci+1);
   if(hitCap&&phaseA.found)return;
   colBlack[c]=-1;
  }
 }
 phaseA.found=null;
 phaseA(0);
 if(phaseA.found)return phaseA.found;
 return (hitCap||budgetHit)?'CAP':null;
}
let pass=0,fail=0,fails=[],notes=[];
function playAndWin(level,sol,label){
 KU.load(level);
 if(KU.ST()!=='playing')throw new Error('loadLevel did not enter playing state');
 for(var r=0;r<sol.length;r++)for(var c=0;c<sol.length;c++)if(sol[r][c]===1)KU.toggle(r,c);
 if(KU.ST()!=='complete')throw new Error('engine checkSolution did NOT accept the independent solution');
 const ov=document.getElementById('completeOverlay');
 if(ov.classList.contains('hidden'))throw new Error('win overlay not shown');
 const sv=JSON.parse(localStorage.getItem('kuromasu_save')||'{}');
 if(!sv.completed||!sv.completed[level.id])throw new Error('win not persisted');
 return sv.completed[level.id].stars;
}
const LV=KU.LV();
if(LV.length!==30)throw new Error('LEVELS.length='+LV.length);
function validateSol(lv,sol){
 const N=lv.size;
 if(lv.sol&&lv.sol.length!==N*N)throw new Error('embedded sol length wrong');
 for(const cl of lv.clues){
  let cnt=0;
  for(let c=0;c<N;c++)if(sol[cl[0]][c]===1)cnt++;
  for(let r=0;r<N;r++)if(sol[r][cl[1]]===1)cnt++;
  if(cnt!==cl[2])throw new Error('sol clue mismatch at ['+cl[0]+','+cl[1]+'] want '+cl[2]+' got '+cnt);
 }
 for(let r=0;r+1<N;r++)for(let c=0;c+1<N;c++)if(sol[r][c]===1&&sol[r+1][c]===1&&sol[r][c+1]===1&&sol[r+1][c+1]===1)throw new Error('sol has 2x2 black');
 let start=null,total=0;
 for(let r=0;r<N;r++)for(let c=0;c<N;c++)if(sol[r][c]===0){total++;if(!start)start=[r,c];}
 if(!start)throw new Error('sol all black');
 const vis=new Set([start[0]+','+start[1]]);const q=[start];
 while(q.length){const t=q.shift();
  for(const d of [[-1,0],[1,0],[0,-1],[0,1]]){const nr=t[0]+d[0],nc=t[1]+d[1],k=nr+','+nc;
   if(nr>=0&&nr<N&&nc>=0&&nc<N&&sol[nr][nc]===0&&!vis.has(k)){vis.add(k);q.push([nr,nc]);}}}
 if(vis.size!==total)throw new Error('sol whites disconnected');
}
for(var li=0;li<LV.length;li++){
 if(globalThis.__ONLY&&String(LV[li].id)!==globalThis.__ONLY)continue;
 try{
  const t0=Date.now();
  let sol,via;
  if(LV[li].sol){
   const N=LV[li].size;sol=[];
   for(let r=0;r<N;r++){const row=[];for(let c=0;c<N;c++)row.push(LV[li].sol[r*N+c]==='1'?1:0);sol.push(row);}
   validateSol(LV[li],sol);
   via='embedded';
  }else{
   solveKuro.leaves=0;
   sol=solveKuro(LV[li].size,LV[li].clues);
   if(sol==='CAP')throw new Error('solver hit cap (leaves='+solveKuro.leaves+')');
   if(!sol)throw new Error('UNWINNABLE: no black/white assignment satisfies engine checkSolution');
   via='independent';
  }
  const stars=playAndWin(LV[li],sol,'L'+LV[li].id);
  pass++;
  if(li===0||li===8||li===16||li===24||li===29)notes.push('L'+LV[li].id+' '+LV[li].size+'x'+LV[li].size+' ['+LV[li].difficulty+']: '+via+' solution ('+(Date.now()-t0)+'ms) validated + won in-engine, stars='+stars);
  document.getElementById('completeOverlay').classList.add('hidden');
 }catch(e){fail++;fails.push('L'+LV[li].id+' EX:'+String(e.message).slice(0,140));document.getElementById('completeOverlay').classList.add('hidden');}
 console.log('  ..L'+LV[li].id+' '+LV[li].size+'x'+LV[li].size+' done');
}
/* daily: engine's own mulberry32 generator produces clue counts from a hidden sol; solve independently */
try{
 KU.daily();
 const dp=KU.getDaily();
 if(!dp)throw new Error('generateDailyPuzzle produced nothing (already done today?)');
 const sol=solveKuro(dp.size,dp.clues);
 if(sol==='CAP')throw new Error('daily solver hit cap');
 if(!sol)throw new Error('UNWINNABLE daily: generated clue set admits no solution');
 playAndWin(dp,sol,'daily');
 pass++;notes.push('daily '+dp.size+'x'+dp.size+' ('+dp.clues.length+' clues): solved independently and won in-engine');
 document.getElementById('completeOverlay').classList.add('hidden');
}catch(e){fail++;fails.push('daily EX:'+String(e.message).slice(0,140));document.getElementById('completeOverlay').classList.add('hidden');}
const te=(globalThis.__timerErrors||[]);
return {pass:pass,fail:fail,total:pass+fail,fails:fails.slice(0,31),verdict:fail===0?'PASS':'FAIL',notes:notes,timerErrors:te.slice(0,5)};
})()`;

let result;
try { result = vm.runInContext(DRIVER, ctx); }
catch (e) { console.error('verify error:', e.stack || e.message); process.exit(1); }
const out = { pass: result.pass, fail: result.fail, total: result.total, verdict: result.fail === 0 ? 'PASS' : 'FAIL' };
if (result.fails && result.fails.length) out.fails = result.fails;
console.log(SLUG + ' in-engine verification: ' + out.pass + '/' + out.total + ' (30 static levels + daily; independent row-pattern solver -> replay via engine toggleCell -> checkSolution win)');
(result.notes || []).forEach(n => console.log('  ' + n));
(result.fails || []).slice(0, 15).forEach(f => console.log('  FAIL ' + f));
if (result.timerErrors && result.timerErrors.length) console.log('timer errors: ' + JSON.stringify(result.timerErrors));
console.log(JSON.stringify(out));
process.exit(out.fail === 0 ? 0 : 1);
